# Site settings
title: 4pFoods
email: dev@ocupop.com
url: "http://client_url.com"
permalink: /:title

# Social sharing
description:
socialshare:
  featured_image:
  twitter:
    username:
    image:

# Google Analytics
analytics_code:


# Collections
collections:
  targets:
    output: true
    layout: default
    permalink: /:title

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap
